#
# OCR4all app
# Application Properties
#
# Author: Herbert Baier (herbert.baier@uni-wuerzburg.de)
# Date:   13.06.2024
#

#
# spring configuration
#
spring.profiles.active:
  - logging-debug
  - msa-api
  - development

#
# server configuration
#
server:
  port: 8080

#
# ocr4all configuration
#
ocr4all:
  message:
    end-point: /event
    topic:
      prefix: /topic
      destination: /spi
  thread.pool.size: 
    standard: 6
    time-consuming: 3
  data.folder: ${user.home}/ocr4all/data
  assemble.folder: ${user.home}/ocr4all/assemble
  projects.folder: ${user.home}/ocr4all/workspace/projects
  calamari:
    logging.discard:
      output: false
      error: false
    processors:
      evaluation.name: calamari-eval
      recognition.name: calamari-predict
      training:
        name: calamari-cross-fold-train
        dataset-filename: dataset.files
      time-consuming: training,recognition
  
#
# logging configuration: console / level info
#
logging:
  file:
    path:
    name:
  level:
    root: INFO
      
---
spring:
    config.activate.on-profile: logging-file

logging:
  file:
    path: /var/log/ocr4all
    name: ocrd.log

---
spring:
    config.activate.on-profile: logging-debug

server.error.include-stacktrace: always
  
logging.level:
  "[de.uniwuerzburg.zpd.ocr4all.application.calamari.msa]": DEBUG

---
spring:
    config.activate.on-profile: calamari-logging-discard


ocr4all.calamari.logging.discard:
  output: true
  error: true

---
spring:
    config.activate.on-profile: docker

ocr4all:
  data.folder: /srv/ocr4all/data
  assemble.folder: /srv/ocr4all/assemble
  projects.folder: /srv/ocr4all/projects

---
spring:
    config.activate.on-profile: development

server:
  port: 9092

ocr4all:
  data.folder: ${user.home}/ocr4all/dev/data
  assemble.folder: ${user.home}/ocr4all/dev/assemble
  projects.folder: ${user.home}/ocr4all/dev/workspace/projects
